name: Test to server

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        env:
          FOO: ${{ secrets.FOO }}
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          envs: FOO
          script: |
            whoami
            echo $FOO
